### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by endymuhardin** [BelajarJavaBareng/bpustaka#2]
Provide information about this project in README.md file, containing:

* brief description about the application: what problem it solves, who will use it, how the user will interact with the application
* technology (programming language, library, framework, tools) used in this project
* how to build the project from source code to executable
* how to contribute to this project
* how to contact project maintainer

**Comment by justhardinal** [comment]
what problem it solves : 

Prospective members can register online and if already registered be able to borrow books online
only members can borrow and return books
can be done online
