### ISSUE TITLE
Code Project Initialize

### ISSUE THREAD

**Issue by galihlasahido** [BelajarJavaBareng/bpustaka#35]
For the base project code first initiate with this i propose :

- spring boot;
  - if its ok, for the template i propose using freemarker;
  - application.properties will be separate base on the database that will be use, for now using postgresql and mysql;
  - package base will be org.belajar.java.bareng.bpustaka;
  - remote shell for maintain application using ssh;
- spring data jpa;
- spring security;

please comment and advice :)

**Comment by endymuhardin** [comment]
Consider implementing profile for database. Choose one database for default setting. E.g : 

```
mvn clean test
``` 
will test to MySQL

```
mvn clean test -Dprofile=pgsql
```
will test against PostgreSQL

**Comment by endymuhardin** [comment]
Package name just use org.bpustaka. Eventhough this is a learning project, but we treat it as production software.

**Comment by galihlasahido** [comment]
ok duly noted, no prob about profiling, i was thinking for separate the file into folders after the mvn install into 
config/
 - application.properties
lib/
 - application.jar
 - libs.... jar
start.sh
templates/
 - file.... ftl

so it wont only in some one large file, any suggestion?

**Comment by endymuhardin** [comment]
Not profiling, profile :)
http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html

**Comment by endymuhardin** [comment]
Profile usage example to distinguish between development and production database. 
http://altfatterz.blogspot.com/2014/10/datasource-configuration-with-spring.html

We can adapt this tutorial to provide the following profile : 
* mysql : mysql for development, installed in programmer's laptop
* postgresql : postgresql for development, installed in programmer's laptop
* openshift : configuration for deploying the app in openshift
* heroku : configuration for deploying the app in heroku

**Comment by endymuhardin** [comment]
Please provide also sample data for integration testing. Use `@SqlGroup` to run setup and teardown script

http://www.leveluplunch.com/java/tutorials/022-preload-database-execute-sql-spring-testing/

**Comment by endymuhardin** [comment]
Done project setup with : 

* one database connection (MySQL)
* one table
* one entity
* one DAO
* one Controller
* one automated tests
