### ISSUE TITLE
Create UI Mockup for Registration Screen 

### ISSUE THREAD

**Issue by dhaowoods** [BelajarJavaBareng/bpustaka#4]
This screen will display a form for registration activity. Registration screen for library system like dspace.org only contains following field email address, first name, last name, contact telephone, can log in. For educational purpose, we may include date, profile picture, religion as thiese fields have different type in JPA.

    Username : textfield, required, alphanumeric, min 4 characters, max 255 chars
    Password : password, required, alphanumeric, min 8 characters, max 255 chars
    Full Name : textfield, required, alphanumeric, min 5 characters, max 255 chars
    Email : email, required, alphanumeric, min 5 characters, max 255 chars
    Contact : masked textfield, required, alphanumeric, min 5 characters, max 255 chars
    Birthdate : Time Picker
    Profile picture : file ( byte[] )
    Country : dropdown (Enum)

**Comment by nirzaq** [comment]
Field : 
1. Username
2. Full Name
3. Email
4. Telephone
5. Birthdate
6. Adresss
7. Profile Picture

I think that's enough for registration page, what about u guys? :)

**Comment by endymuhardin** [comment]
Please provide also input field type, e.g : textfield, dropdown, combo, radio, etc

**Comment by endymuhardin** [comment]
And while we're at it, include validation rule as well. For example : 

1. Username : textfield, required, alphanumeric, min 4 characters, max 255 chars

**Comment by dhaowoods** [comment]
1. Username :  textfield, required, alphanumeric, min 4 characters, max 255 chars
2. Password : password, required, alphanumeric, min 8 characters, max 255 chars
3. Full Name :  textfield, required, alphanumeric, min 5 characters, max 255 chars
4. Email : email, required, alphanumeric, min 5 characters, max 255 chars
5. Contact : masked textfield, required, alphanumeric, min 5 characters, max 255 chars
6. Can Log in : boolean
7. Birthdate : date
8. Profile picture : file ( byte[] )
9. Country : dropdown (Enum)

**Comment by nirzaq** [comment]
What's "Can Log in" field? Are we put it on the screen or it's hidden?

**Comment by dhaowoods** [comment]
it will be shown in screen, it will be used for authentication. According to dspace, this field will free us from having to deal with cascade delete. So, in order to revoke user's right we just need to set this field to false.

**Comment by nirzaq** [comment]
can u show me an example? Or website registration using it?

**Comment by dhaowoods** [comment]
http://publikasiilmiah.ums.ac.id and https://dspace.mit.edu ... ah, pardon me, I forgot, I should remove this field from user registration, this field only visible from admin panel >.<

**Comment by moohat** [comment]
how can I contribute?

**Comment by nirzaq** [comment]
@moohat Which fields that's we have to include in app registration page? We discussed what's field that's we have to include in our app here. :)

**Comment by robert589** [comment]
Birthdate can use timePicker
Contact put it into two textfields which are the country code and the phone number

Please update

**Comment by dhaowoods** [comment]
yes.. okey..

**Comment by dhaowoods** [comment]
ah, I almost forget, in [primfaces](http://www.primefaces.org/showcase/ui/input/inputMask.xhtml) there is a masked field. but I don't know whether mock up should be implementation independent or not. How about mr @endymuhardin , what is the front end technology for this project?

**Comment by gondok** [comment]
country not have to be included, it's my assumption

**Comment by swhp** [comment]
about password how about min characters is set into 5 or 6?
i think 8 it's to long
